"""Color themes for the keyboard tester UI."""

LIGHT = {
    "bg": "#f0f0f5",
    "bg_secondary": "#ffffff",
    "accent": "#4361ee",
    "accent_hover": "#3a56d4",
    "key_bg": "#e2e2ea",
    "key_fg": "#1a1a2e",
    "key_border": "#c8c8d4",
    "key_active": "#ff3333",
    "key_active_fg": "#ffffff",
    "key_tested": "#d4edda",
    "key_tested_fg": "#555555",
    "key_stuck": "#ff6b6b",
    "key_stuck_fg": "#ffffff",
    "text": "#1a1a2e",
    "text_dim": "#6b7280",
    "listbox_bg": "#ffffff",
    "listbox_fg": "#1a1a2e",
    "scrollbar": "#c8c8d4",
    "btn_fg": "#ffffff",
    "progress_bg": "#e2e2ea",
    "progress_fill": "#2ecc71",
    "progress_full": "#27ae60",
    "ghost": "#ff9800",
    "ghost_fg": "#ffffff",
    "combo_pass": "#2ecc71",
    "combo_pending": "#e2e2ea",
    "combo_pending_fg": "#888888",
    "combo_active": "#ff3333",
}

DARK = {
    "bg": "#1a1a2e",
    "bg_secondary": "#16213e",
    "accent": "#e94560",
    "accent_hover": "#ff6b81",
    "key_bg": "#2c2c54",
    "key_fg": "#eaeaea",
    "key_border": "#474787",
    "key_active": "#ff1744",
    "key_active_fg": "#ffffff",
    "key_tested": "#2d4a3e",
    "key_tested_fg": "#8a9a90",
    "key_stuck": "#b71c1c",
    "key_stuck_fg": "#ffffff",
    "text": "#eaeaea",
    "text_dim": "#7f8fa6",
    "listbox_bg": "#16213e",
    "listbox_fg": "#dcdde1",
    "scrollbar": "#474787",
    "btn_fg": "#eaeaea",
    "progress_bg": "#2c2c54",
    "progress_fill": "#44bd32",
    "progress_full": "#2ecc71",
    "ghost": "#ff6d00",
    "ghost_fg": "#ffffff",
    "combo_pass": "#44bd32",
    "combo_pending": "#2c2c54",
    "combo_pending_fg": "#7f8fa6",
    "combo_active": "#ff1744",
}
